updated dependencies
Softonix/frontend-guidelines pull request #34
Opened 2023-10-13 09:28 UTC by oleh-selivanov

2023-10-13 15:46 UTC, v-romanyuk commented on package.json
> +    "unplugin-auto-import": "0.16.6",
Ти протестив чи всі автоімпорти скриптів зі всіх папок працюють? Там стояла саме 0.15.2 без '^' чи '~' тому що версії вище не працювали як потрібно

2023-10-13 15:46 UTC, v-romanyuk commented on package.json
> +    "unplugin-auto-import": "0.16.6",
Ти протестив чи всі автоімпорти скриптів зі всіх папок працюють? Там стояла саме 0.15.2 без '^' чи '~' тому що версії вище не працювали як потрібно

2023-10-13 15:46 UTC, v-romanyuk commented on package.json
> +    "unplugin-auto-import": "0.16.6",
Ти протестив чи всі автоімпорти скриптів зі всіх папок працюють? Там стояла саме 0.15.2 без '^' чи '~' тому що версії вище не працювали як потрібно

2023-10-13 16:00 UTC, v-romanyuk commented on src/plugins/i18n/translations/de/index.ts
> +import deLocale from 'element-plus/es/locale/lang/de'
по документації зараз імпортують ось так
import zhCn from 'element-plus/dist/locale/zh-cn.mjs'.
Але з es теж ок. Поправ ще імпорт TranslatePair з app.vue

2023-10-13 16:02 UTC, v-romanyuk commented on src/views/example-view/ExampleView.vue
>      await exampleStore.getExampleVar()
це має бути в блоці try

2023-10-13 16:03 UTC, v-romanyuk requested changes

2023-10-13 16:03 UTC, v-romanyuk commented on src/views/example-view/ExampleView.vue
> +    console.log(err)
тут вже тоді краще console.error

2023-10-13 17:33 UTC, oleh-selivanov commented on package.json
> +    "unplugin-auto-import": "0.16.6",
Та, ніби все правильно

2023-10-13 17:40 UTC, oleh-selivanov commented on src/plugins/i18n/translations/de/index.ts
> +import deLocale from 'element-plus/es/locale/lang/de'
`import zhCn from 'element-plus/dist/locale/zh-cn.mjs'.` але тоді ерорить тайпскрипт, тому `import deLocale from 'element-plus/es/locale/lang/de'` теж підходить

2023-10-23 13:19 UTC, v-romanyuk approved these changes

2023-10-23 13:19 UTC, merged